server:
  port: 8080


sysConf:
  handlerJarFileBasePath: C:\yxcloud\handlers
  decodePluginBasePath: C:\yxcloud\decodeplugins
  resourcePath: C:\yxcloud\resources
  debugPort: 10373
  defaultServerPort: 8083

















