server:
  port: 8083


sysConf:
  handlerJarFileBasePath: C:\yxcloud\handlers
  decodePluginBasePath: C:\yxcloud\decodeplugins
  resourcePath: C:\yxcloud\resources
  debugPort: 8088
  defaultServerPort: 8089

















